### ISSUE TITLE
Alpha nav bar jumps too far down page

### ISSUE THREAD

**Issue by seancorfield** [cybersonic/luceedocs#8]
On tags/functions, if you click on one of the alpha nav bar elements (or the object nav bar on the objects page), you are jumped to the _second_ element in the list, not the first one. I think this might be due to the black header bar being deep enough to obscure the first element - which might also be the reason for the search drop down being obscured?

**Comment by jclausen** [comment]
Submitted pull request #9 with a fix for this. It has to do with the CSS fixed positioning of the navbar.  Added a CSS pseudo element before to reposition the anchor relative to the nav.

**Comment by cybersonic** [comment]
Great work sir. Will try and get this live over the weekend.
